/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Calculator;

import java.io.IOException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        boolean running = true;
        while (running) {
            double answer = 0.0;
            printMode();
            double mode = getInput();
            if (mode == 1) {
                NumberPair nPair = getTwoNumbers(false);
                answer = nPair.getX() + nPair.getY();
                System.out.println("" + nPair.getY() + " + " + nPair.getX() + " = " + answer);
                pause();
            } else if (mode == 2) {
                NumberPair nPair = getTwoNumbers(false);
                answer = nPair.getX() - nPair.getY();
                System.out.println("" + nPair.getY() + " - " + nPair.getX() + " = " + answer);
                pause();
            } else if (mode == 3) {
                NumberPair nPair = getTwoNumbers(false);
                answer = nPair.getX() * nPair.getY();
                System.out.println("" + nPair.getY() + " x " + nPair.getX() + " = " + answer);
                pause();
            } else if (mode == 4) {
                NumberPair nPair = getTwoNumbers(true);
                answer = nPair.getX() / nPair.getY();
                System.out.println("" + nPair.getY() + " / " + nPair.getX() + " = " + answer);
                pause();
            } else if (mode == 5) {
                running = false;
                break;
            }
        }
        System.out.println("Goodbye");
    }

    public static void printMode() {
        System.out.println("Please select mode of operation.");
        System.out.println("1. Addition");
        System.out.println("2. Subtraction");
        System.out.println("3. Multiplication");
        System.out.println("4. Division");
        System.out.println("5. Quit");
    }

    public static double getInput() {
        Scanner inputScanner = new Scanner(System.in);
        while (!inputScanner.hasNextDouble()) { //Sanitize the input and ensure only numbers are entered.
            System.out.println("Please only enter a number.");
            inputScanner.next();
        }
        return inputScanner.nextDouble();
    }

    public static NumberPair getTwoNumbers(boolean divison) {
        NumberPair nPair = new NumberPair();
        if (divison) {
            while (nPair.getX() == 0) {
                System.out.print("First Number:");
                nPair.setX(getInput());
                if (nPair.getX() == 0) {
                    System.out.println("You can't divide with zero");
                }
            }
            while (nPair.getY() == 0) {
                System.out.print("Second Number:");
                nPair.setY(getInput());
                if (nPair.getY() == 0) {
                    System.out.println("You can't divide with zero");
                }
            }
        } else {
            System.out.print("First Number:");
            nPair.setX(getInput());
            System.out.println();
            System.out.print("Second Number:");
            nPair.setY(getInput());
        }
        return nPair;
    }

    public static void pause() {
        try {
            System.out.println("Press enter to continue...");
            System.in.read();
        } catch (IOException ignored) {

        }
    }
}
